version: '2'
services:
    jlearning-app:
        image: jlearning
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jlearning-mysql:3306/jlearning?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jlearning-mysql:
        extends:
            file: mysql.yml
            service: jlearning-mysql
